/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication10;

import javax.swing.JOptionPane;

/**
 *
 * @author Adolfo Castillo, Andrea Sanchez, Luciano Rojas 
 */
public class dashboard extends javax.swing.JFrame {

    public static HashTable hashTable;

    /**
     * Creates new form dashboard
     */
    public dashboard(HashTable hashTable) {
        initComponents();
        this.hashTable = hashTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VerPatronesAlmacenados = new javax.swing.JToggleButton();
        Patrones = new javax.swing.JComboBox<>();
        BuscarPatron = new javax.swing.JButton();
        VerPatronMenosFrecuente = new javax.swing.JButton();
        VerPatronMasFrecuente = new javax.swing.JButton();
        VerReporteDeColisiones = new javax.swing.JButton();
        VerTripletasPorAminoacido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerPatronesAlmacenados.setText("Mostrar patrones almacenados");
        VerPatronesAlmacenados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPatronesAlmacenadosActionPerformed(evt);
            }
        });
        jPanel1.add(VerPatronesAlmacenados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Patrones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Patrones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, -1));

        BuscarPatron.setText("Buscar un patrón");
        BuscarPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPatronActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarPatron, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        VerPatronMenosFrecuente.setText("Ver patrón menos frecuente");
        VerPatronMenosFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPatronMenosFrecuenteActionPerformed(evt);
            }
        });
        jPanel1.add(VerPatronMenosFrecuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        VerPatronMasFrecuente.setText("Ver patrón más frecuente");
        VerPatronMasFrecuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPatronMasFrecuenteActionPerformed(evt);
            }
        });
        jPanel1.add(VerPatronMasFrecuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        VerReporteDeColisiones.setText("Ver reporte de colisiones");
        jPanel1.add(VerReporteDeColisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, -1));

        VerTripletasPorAminoacido.setText("Ver tripletas por aminoácido");
        jPanel1.add(VerTripletasPorAminoacido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        Resultados.setColumns(20);
        Resultados.setRows(5);
        jScrollPane1.setViewportView(Resultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 270, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPatronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarPatronActionPerformed

    private void VerPatronesAlmacenadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPatronesAlmacenadosActionPerformed
        // Crear árbol binario
        ArbolBinario arbol = new ArbolBinario();

        // Recorrer la tabla hash directamente SIN ArrayList
        for (int i = 0; i < this.hashTable.getTabla().length; i++) {
            NodoLista actual = this.hashTable.getTabla()[i].cabeza;
            while (actual != null) {
                arbol.insertar(actual.dato); // Insertar directamente en el árbol
                actual = actual.siguiente;
            }
        }

        // Obtener el texto ordenado
        String resultado = arbol.inOrdenComoTexto();

        // Mostrar en el JTextArea
        Resultados.setText(resultado);
    }//GEN-LAST:event_VerPatronesAlmacenadosActionPerformed

    private void VerPatronMasFrecuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPatronMasFrecuenteActionPerformed
        PatronADN patron = hashTable.obtenerPatronMasFrecuente();
        String resultado = "";
            
        if (patron != null) {
            resultado += "Tripleta más frecuente: " + patron.tripleta;
            resultado += "\nFrecuencia: " + (patron.frecuencia);
            resultado += "\nUbicaciones: " + (patron.ubicaciones.obtenerUbicacionesComoTexto());

            Resultados.setText(resultado.toString());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron patrones.");
        }
    }//GEN-LAST:event_VerPatronMasFrecuenteActionPerformed

    private void VerPatronMenosFrecuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPatronMenosFrecuenteActionPerformed
        PatronADN patron = hashTable.obtenerPatronMenosFrecuente();
        String resultado = "";
            
        if (patron != null) {
            resultado += "Tripleta menos frecuente: " + patron.tripleta;
            resultado += "\nFrecuencia: " + (patron.frecuencia);
            resultado += "\nUbicaciones: " + (patron.ubicaciones.obtenerUbicacionesComoTexto());

            Resultados.setText(resultado.toString());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron patrones.");
        }
    }//GEN-LAST:event_VerPatronMenosFrecuenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard(hashTable).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPatron;
    private javax.swing.JComboBox<String> Patrones;
    private javax.swing.JTextArea Resultados;
    private javax.swing.JButton VerPatronMasFrecuente;
    private javax.swing.JButton VerPatronMenosFrecuente;
    private javax.swing.JToggleButton VerPatronesAlmacenados;
    private javax.swing.JButton VerReporteDeColisiones;
    private javax.swing.JButton VerTripletasPorAminoacido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
